export const notifications = [
    {
        id: "1",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você recebeu um novo pagamento de R$ 50,00 de VCM",
        type: "Recebimento Pix",
        ativo: true,
        entry: true,
    },
    {
        id: "2",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você realizou um novo pagamento de R$ 100,00 para VCM",
        type: "Cartão de Debito",
        ativo: false,
        entry: false,
    },
    {
        id: "3",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você realizou um novo pagamento de R$ 10,00 para VCM",
        type: "Cartão de Crédito",
        ativo: false,
        entry: false,
    },
    {
        id: "4",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você realizou um novo pagamento de R$ 59,00 para VCM",
        type: "Cartão de Debito",
        ativo: true,
        entry: false,
    },
    {
        id: "5",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você realizou um novo pagamento de R$ 75,00 para VCM",
        type: "Cartão de Crédito",
        ativo: true,
        entry: false,
    },
    {
        id: "6",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você recebeu um novo pagamento de R$ 36,00 de VCM",
        type: "Recebimento Pix",
        ativo: false,
        entry: true,
    },
    {
        id: "7",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você recebeu um novo pagamento de R$ 100,00 de VCM",
        type: "Recebimento Pix",
        ativo: false,
        entry: true,
    },
    {
        id: "8",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você recebeu um novo pagamento de R$ 80,00 de VCM",
        type: "Recebimento Pix",
        ativo: true,
        entry: true,
    },
    {
        id: "9",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você realizou um novo pagamento de R$ 90,00 para VCM",
        type: "Cartão de Crédito",
        ativo: false,
        entry: false,
    },
    {
        id: "10",
        datetime: "2021-05-01T00:00:00.000Z",
        title: "Você realizou um novo pagamento de R$ 30,00 para VCM",
        type: "Cartão de Débito",
        ativo: true,
        entry: false,
    }
]
