
export const transactions = [
    {
        id: "1",
        title: "Netflix",
        subtitle: "Pagamento referente à Netflix",
        price: "49.99",
        icon: "netflix",
    },
    {
        id: "2",
        title: "PlayStation",
        subtitle: "Pagamento referente à PS Store",
        price: "99.99",
        icon: "playstation",
    },
    {
        id: "3",
        title: "Steam",
        subtitle: "Pagamento referente à Steam",
        price: "999.99",
        icon: "steam",
    },
    {
        id: "4",
        title: "Apple Music",
        subtitle: "Pagamento referente à Apple Music",
        price: "99.99",
        icon: "applemusic",
    },
    {
        id: "5",
        title: "Google Play",
        subtitle: "Pagamento referente ao Google Play",
        price: "99.99",
        icon: "google-play",
    },
    {
        id: "6",
        title: "Netflix",
        subtitle: "Pagamento referente à Netflix",
        price: "49.99",
        icon: "netflix",
    },
    {
        id: "7",
        title: "PlayStation",
        subtitle: "Pagamento referente à PS Store",
        price: "99.99",
        icon: "playstation",
    },
    {
        id: "8",
        title: "Steam",
        subtitle: "Pagamento referente à Steam",
        price: "999.99",
        icon: "steam",
    },
    {
        id: "9",
        title: "Apple Music",
        subtitle: "Pagamento referente à Apple Music",
        price: "99.99",
        icon: "applemusic",
    },
    {
        id: "10",
        title: "Google Play",
        subtitle: "Pagamento referente ao Google Play",
        price: "99.99",
        icon: "google-play",
    },
    {
        id: "11",
        title: "Netflix",
        subtitle: "Pagamento referente à Netflix",
        price: "49.99",
        icon: "netflix",
    },
    {
        id: "12",
        title: "PlayStation",
        subtitle: "Pagamento referente à PS Store",
        price: "99.99",
        icon: "playstation",
    },
    {
        id: "13",
        title: "Steam",
        subtitle: "Pagamento referente à Steam",
        price: "999.99",
        icon: "steam",
    },
    {
        id: "14",
        title: "Apple Music",
        subtitle: "Pagamento referente à Apple Music",
        price: "99.99",
        icon: "applemusic",
    },
    {
        id: "15",
        title: "Google Play",
        subtitle: "Pagamento referente ao Google Play",
        price: "99.99",
        icon: "google-play",
    },
    {
        id: "16",
        title: "Netflix",
        subtitle: "Pagamento referente à Netflix",
        price: "49.99",
        icon: "netflix",
    },
    {
        id: "17",
        title: "PlayStation",
        subtitle: "Pagamento referente à PS Store",
        price: "99.99",
        icon: "playstation",
    },
    {
        id: "18",
        title: "Steam",
        subtitle: "Pagamento referente à Steam",
        price: "999.99",
        icon: "steam",
    },
    {
        id: "19",
        title: "Apple Music",
        subtitle: "Pagamento referente à Apple Music",
        price: "99.99",
        icon: "applemusic",
    },
    {
        id: "20",
        title: "Google Play",
        subtitle: "Pagamento referente ao Google Play",
        price: "99.99",
        icon: "google-play",
    },
]
